### ISSUE TITLE
Fix package name in examples

### ISSUE THREAD

**Issue by geoidesic** [Kruptein/planarally-dice#4]
Received malformed response from registry for "babylonjs-dice". The registry may be down.

**Comment by Kruptein** [comment]
Oh my bad, it renamed to `@planarally/dice`!

**Comment by Kruptein** [comment]
I've fixed the examples in the dev branch.

- fixed import
- fixed older APIs that have been reworked
- Added example meshes

The webpack example should be buildable and runnable if you have a simple http server in the examples folder `e.g. python3 -m http.server` or something similar

**Comment by geoidesic** [comment]
Hmm. Nope.
I did `npm run build` and got this (after quite a long wait and I thought my laptops fans were going to exit the building):
```
npm run build

> planarally-dice-webpack@1.0.0 build
> rimraf dist && webpack

asset bundle.js 4.83 MiB [emitted] [minimized] [big] (name: main)
orphan modules 8.31 MiB [orphan] 897 modules
runtime modules 1.13 KiB 5 modules
cacheable modules 10.1 MiB
  modules by path ./ 10.1 MiB
    ./src/index.ts 3.38 KiB [built] [code generated]
    ./node_modules/@babylonjs/core/index.js + 869 modules 8.3 MiB [built] [code generated]
    ./node_modules/@planarally/dice/dist/index.js + 7 modules 14.2 KiB [built] [code generated]
    ./node_modules/ammo.js/builds/ammo.js 1.8 MiB [built] [code generated]
  path (ignored) 15 bytes [built] [code generated]
  fs (ignored) 15 bytes [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  bundle.js (4.83 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (4.83 MiB)
      bundle.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

Then I tried `python3 -m http.server` and all I get is a blank page.

**Comment by geoidesic** [comment]
I think the problem is that the meshes etc. folders are outside of the webpack folder, and since the web server index is inside the webpack folder, it can't reach them.

**Comment by geoidesic** [comment]
I tried running the web server from one folder up but got the same errors in console.

**Comment by Kruptein** [comment]
The meshes are provided as an example and thats why they're in the example folder.  The idea is that if you incorporate this somewhere you have a place to host the meshes. (or in the future a default set will be included in the lib itself).

That said you can perfectly run this with the python server if you start the server in the examples folder.  How are you accessing the webpack example? If you host the server in the examples folder it should work from the `http://localhost:8000/webpack/index.html` endpoint. Another approach is to simply copy the meshes inside the webpack folder and adjust the load url.

A last thing, the build really shouldn't take _that_ long.

**Comment by geoidesic** [comment]
Ah.. I was trying from 0.0.0.0, as the python server instructed. Didn't try localhost. Eureka! It works!

**Comment by Kruptein** [comment]
Haha woo!

Yeah it's still in an early phase, didn't really expect someone to find it ;)
But I expect to work this out more properly as I plan to use it for my own program (planarally).

So feel free to let me know of any complaints

**Comment by geoidesic** [comment]
What is planarally going to be?

**Comment by Kruptein** [comment]
It's my virtual tabletop software :D (https://github.com/Kruptein/PlanarAlly)
