### ISSUE TITLE
Can't yarn install @planarally-dice

### ISSUE THREAD

**Issue by geoidesic** [Kruptein/planarally-dice#5]
`yarn add @planarally-dice`
error An unexpected error occurred: "https://registry.yarnpkg.com/@planarally-dice: Request \"https://registry.yarnpkg.com/@planarally-dice\" returned a 405".

Same error with `yarn add @planarally/dice`. Literally the same; which is odd because I'd expect the error to at least reflect the punctuation change from - to /.

Seems to work with npm... but I can't use npm because it breaks other things.
I tried using npm first and then yarn afterwards; which seems to be a workaround. So I can do this:
```
npm I @planarall-dice
yarn install
rm -rf package-lock.json
```
Oddly after the npm I, then `yarn add @planarally-dice` still throws the error, but `yarn add @planarally/dice no longer does. Quite confusing.

**Comment by Kruptein** [comment]
It seems to exist on the yarn registry though https://registry.yarnpkg.com/@planarally/dice

**Comment by Kruptein** [comment]
But I'll check it out tomorrow/sunday. I'm chasing a bug with Ammo.js so I might do an update anyway and double check the examples to see if they properly work

**Comment by geoidesic** [comment]
Ok tx. I haven't figured out how to run the examples, so something in the readme about that would be awesome.

**Comment by Kruptein** [comment]
Will do! Sorry it's still very bare bones

**Comment by geoidesic** [comment]
Looks like this was a node version error. Once I used v16 it installs via yarn.
